### ISSUE TITLE
Interop failure with rust-libp2p yamux

### ISSUE THREAD

**Issue by p-shahi** [ChainSafe/js-libp2p-yamux#48]
See: https://github.com/libp2p/test-plans/pull/178 and https://github.com/libp2p/rust-libp2p/pull/3013
This occurs on the latest version i.e. 4.0.1

Creating this here in case this is an issue within this module

cc: @wemeetagain

**Comment by p-shahi** [comment]
Discussion in libp2p-implementers on slack: https://filecoinproject.slack.com/archives/C03K82MU486/p1683032246412229

**Comment by maschad** [comment]
In https://github.com/libp2p/rust-libp2p/pull/3013 upon receiving a ping, the queue [doesn't properly flush](https://github.com/libp2p/rust-libp2p/blob/c224ffe01266e33101b609c10772fc116f7cf929/protocols/ping/src/protocol.rs#LL81C6-L81C6) before notifying the buffer that it has received a ping, which leads the rust peer to try and open a new ping instead of returning a _pong_ (an **ACK**).  This will be addressed on the PR.
